name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Move frontend build to backend resources
        run: |
          mkdir -p src/main/resources/static
          mv dist/* src/main/resources/static/

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build backend with Maven
        run: mvn clean package

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: uncwtestwebapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
